# Serie de Fibonacci

La serie de Fibonacci se usa para modelar crecimiento de poblaciones de bichos. Por ejemplo: conejitos. Se empieza con un granero vacío, en $t_{0}$, en $t_{1}$ una parejita de conejos se metió quién sabe cómo y usan ese tiempo para instalarse, en $t_{1}$ sigue la misma parejita, pero una nueva parejita ya se está gestando. En $t_{3}$ nace una segunda pareja, ahora son dos: la nueva usa ese tiempo para instalarse y la primera otra vez está gestando una nueva.

Uno puede imaginarse el área que ocupa la población de conejitos viendo esta figura:

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/34%2A21-FibonacciBlocks.png/300px-34%2A21-FibonacciBlocks.png">

También puede usarse la serie de Fibonacci para aproximar la proporción áurea:

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Fibonacci_spiral_34.svg/320px-Fibonacci_spiral_34.svg.png">

Más información en el artículo ["Sucesión de Fibonacci" en la Wikipedia](https://es.wikipedia.org/wiki/Sucesi%C3%B3n_de_Fibonacci).

La ecuación de recurrencia de segundo orden es así:

$F_{k+2}=F_{k+1}+F_{k}$
<a name="eq1">.......eq1</a>

Con valores iniciales $F_{0}=1, F_{1}=1$ la secuencia es:

$0,1,1,2,3,5,8,13,...$



Hay dos formas de obtener el k-ésimo valor de esta serie. Usando la ecuación de recurrencia <a href="#eq1">eq1</a> o usando esta fórmula cerrada:

$F_{k}=\frac{1}{\sqrt{5}}\left[\left(\frac{1+\sqrt{5}}{2}\right)^{k}-\left(\frac{1-\sqrt{5}}{2}\right)^{k}\right]$<a name="eq2">.......eq2</a>

## Teorema

Sea $A$ una matriz cuadrada de dimensión n. Si $A$ tiene n valores propios distintos

$\lambda_{1},\lambda_{2},...,\lambda_{n},$

con vectores propios correspondientes 

$v_{1},v_{2},...,v_{n},$

entonces $A$ es diagonalizable, o sea existen las matrices $P$ y $D$ de dimensión n tales que $D$ es una matriz diagonal y

$P^{-1}AP=D$

$D=\left[\begin{array}{cccc}
 \lambda_{1}  &  0  &  \cdots\  &  0\\
0  &  \lambda_{2}  &  \cdots\  &  0\\
\vdots\  &  \vdots\  &  \ddots\  &  \vdots\\
0  &  0  &  0  &  \lambda_{n} 
\end{array}\right]$

$P$ es la matriz cuyas columnas son los vectores propios.

$P=\left[v_{1}|v_{2}|...|v_{n}\right]$


Se generan los núneros de la sucesión de Fibonacci en las coordenadas de los vectores en $R2$ a partir de la condición inicial

$u_{0}=\left[\begin{array}{c}
F_{1}\\
F_{0}
\end{array}\right]=\left[\begin{array}{c}
1\\
0
\end{array}\right]$

Sea

$A=\left[\begin{array}{cc}
1 & 1\\
1 & 0
\end{array}\right]$
<a name="eq3">.......eq3</a>

entonces, si

$u_{k}=A\mathbf{u}_{k-1}$
<a name="eq4">.......eq4</a>

para $k=1,2,3...$

$u_{k}=\left[\begin{array}{c}
F_{k+1}\\
F_{k}
\end{array}\right]$

$u_{k}=A^{k}\mathbf{u}_{0}$
<a name="eq5">.......eq5</a>

----------
Se usa la ecuación <a href="#eq4">eq4</a> para generar algunos $u$.

$u_{0}=\left[\begin{array}{c}
F_{1}\\
F_{0}
\end{array}\right]=\left[\begin{array}{c}
1\\
0
\end{array}\right]$

$u_{1}=\left[\begin{array}{cc}
1 & 1\\
1 & 0
\end{array}\right]
\left[\begin{array}{c}
1\\
0
\end{array}\right]=\left[\begin{array}{c}
1\\
1
\end{array}\right]$

$u_{2}=\left[\begin{array}{cc}
1 & 1\\
1 & 0
\end{array}\right]
\left[\begin{array}{c}
1\\
1
\end{array}\right]=\left[\begin{array}{c}
2\\
1
\end{array}\right]$


$u_{3}=\left[\begin{array}{cc}
1 & 1\\
1 & 0
\end{array}\right]
\left[\begin{array}{c}
2\\
1
\end{array}\right]=\left[\begin{array}{c}
3\\
2
\end{array}\right]$


$u_{4}=\left[\begin{array}{cc}
1 & 1\\
1 & 0
\end{array}\right]
\left[\begin{array}{c}
3\\
2
\end{array}\right]=\left[\begin{array}{c}
5\\
3
\end{array}\right]$


$u_{5}=\left[\begin{array}{cc}
1 & 1\\
1 & 0
\end{array}\right]
\left[\begin{array}{c}
5\\
3
\end{array}\right]=\left[\begin{array}{c}
8\\
5
\end{array}\right]$


$u_{6}=\left[\begin{array}{cc}
1 & 1\\
1 & 0
\end{array}\right]
\left[\begin{array}{c}
8\\
5
\end{array}\right]=\left[\begin{array}{c}
13\\
8
\end{array}\right]$


A continuación pongamos a prueba la <a href="#eq5">eq5</a>.

In [3]:
# importamos bibliotecas cómputo de matrices
import numpy as np

A = np.matrix([[1, 1],
               [1, 0]])

# para k=3 A se multiplica por sí misma tres veces:
A*A*A

matrix([[3, 2],
        [2, 1]])

In [6]:
u0 = [1,
      0]

# u3
np.dot(A*A*A,
       u0)

matrix([[3, 2]])

## Polinomio característico

Como $\lambda$ es un valor propio de $A$

$(\lambda I-A)\overrightarrow{X}=\overrightarrow{0}$

un eigenvector que sea su solución depende de que

$\det(\lambda I-A)=\det\left(\left[\begin{array}{cc}
\lambda & 0\\
0 & \lambda
\end{array}\right]-\left[\begin{array}{cc}
1 & 1\\
1 & 0
\end{array}\right]\right)=\overrightarrow{0}$

Luego

$\det\left(\left[\begin{array}{cc}
\lambda-1 & -1\\
-1 & \lambda
\end{array}\right]\right)=(\lambda-1)\lambda-(-1)(-1)=\lambda^{2}-\lambda-1$
 
## Valores propios

Para obtener los valores propios usamos la fórmula general para encontrar valores de $\lambda$ que satisfagan el polinomio característico

$p(\lambda)=\lambda^{2}-\lambda-1$

Acá la fórmula general:
$x=\frac{-b\pm\sqrt{b^{2}-4ac}}{2a}$
 
$\lambda=\frac{1\pm\sqrt{-1^{2}-4(1)(-1)}}{2(1)}=\frac{1\pm\sqrt{1+4}}{2}$

Por eso

$\begin{array}{c}
\lambda_{1}=\frac{1+\sqrt{5}}{2}\\
\lambda_{2}=\frac{1-\sqrt{5}}{2}
\end{array}$
<a name="eq6">.......eq6</a>
 
 
 ## Vectores propios
 
$\left[\begin{array}{cc}
\lambda-1 & -1\\
-1 & \lambda
\end{array}\right]\overrightarrow{X}=\left[\begin{array}{cc}
\lambda-1 & -1\\
-1 & \lambda
\end{array}\right]\left[\begin{array}{c}x_{1}\\
x_{2}\end{array}\right]$

Equivale al sistema de ecuaciones

$(\lambda-1)x_{1}-x_{2}=0$....(1)

$-x_{1}+\lambda x_{2}=0$.....(2)

Despejando $x_{1}$ en (2)

$x_{1}=\lambda x_{2}$

que sustituyendo en (1)

$(\lambda-1)\lambda x_{2}-x_{2}=0$

factorizamos $x_{2}$ 

$x_{2}\left[(\lambda-1)\lambda-1\right]=0$

sea $x_{2}=1$ en (2)

$-x_{1}+\lambda=0$

$x_{1}=\lambda$

Por eso los vectores propios son

$v_{1}=\left[\begin{array}{c}
\lambda_{1}\\
1
\end{array}\right],\: v_{2}=\left[\begin{array}{c}
\lambda_{2}\\
1
\end{array}\right]$
<a name="eq7">.......eq7</a>


## Matriz de transición P

Con $v_{1}$ y $v_{2}$ formamos la matriz $P$.

Para obtener la matriz invertida $P^{-1}$ Anton y Rorres muestran este teorema:

Si

$A=\left[\begin{array}{cc}
a & b\\
c & d
\end{array}\right]$
 
entonces

$A^{-1}=\frac{1}{ad-bc}\left[\begin{array}{cc}
d & -b\\
-c & a
\end{array}\right]$
 
Teniendo la matriz

$P=\left[\begin{array}{cc}
\lambda_{1} & \lambda_{2}\\
1 & 1
\end{array}\right]$

entonces

$P^{-1}=\frac{1}{\lambda_{1}-\lambda_{2}}\left[\begin{array}{cc}
1 & -\lambda_{2}\\
-1 & \lambda_{1}
\end{array}\right]$

Para comprobar

$P^{-1}AP=\left[\begin{array}{cc}
\lambda_{1} & 0\\
0 & \lambda_{2}
\end{array}\right]=D$
 
basta con multiplicar las matrices $P^{-1}AP$. Como está laborioso hagámoslo con numpy en la siguiente celda.


In [11]:
from math import sqrt

# eigenvalores
l1=(1+sqrt(5))/2.0
l2=(1-sqrt(5))/2.0

print("lambda1=%s, lambda2=%s" % (l1,l2))

# la matriz de transicion P
P = np.matrix([[l1, l2],
               [1,  1]])

# valores como 1.66533454e-16 son como ceros! esto pasa por no hacerlo analiticamente
(P**-1)*A*P

lambda1=1.618033988749895, lambda2=-0.6180339887498949


matrix([[  1.61803399e+00,  -1.11022302e-16],
        [  1.66533454e-16,  -6.18033989e-01]])

In [ ]:
# importamos bibliotecas para plotear
import matplotlib
import matplotlib.pyplot as plt

# para desplegar los plots en el notebook
%matplotlib inline